market:
  app:
    name: liven-market
    secret: ${JWT_SECRET:my-market-secret}
  port: 8285
  log:
    level: DEBUG
  database:
    schema: ${DB_SCHEMA:MarketApp}
    name: ${DB_NAME:LivenMarketDataBase}
    username: ${DB_CONNECTION_USER_NAME:sa}
    password: ${DB_CONNECTION_PASSWORD:password}
    ddlAuto: validate
    showSql: false
    enableFlyway: ${RUN_FLYWAY:true}

spring:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: detect
  application:
    name: ${market.app.name}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    url: jdbc:h2:mem:${market.database.name};MODE=PostgreSQL;AUTO_RECONNECT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS MarketApp;DB_CLOSE_DELAY=-1
    username: ${market.database.username}
    password: ${market.database.password}
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      order_by:
        default_null_ordering: last
    hibernate:
      ddl-auto: ${market.database.ddlAuto}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${market.database.showSql}
    database-platform: org.hibernate.dialect.H2Dialect
  #    defer-datasource-initialization: true
  flyway:
    enabled: ${market.database.enableFlyway}
    schemas: ${market.database.schema}
    locations: filesystem:src/main/resources/scripts/migrations
    user: ${market.database.username}
    password: ${market.database.password}
    baseline-on-migrate: true
  web:
    locale: pt_BR
    resources:
      add-mappings: false
  mvc:
    format:
      date: dd/MM/yyyy
  servlet:
    multipart:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:${market.port}}
  servlet:
    context-path: ${CONTEXT_PATH:/market}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${market.app.name}]){magenta}%clr(%X{cdTransacao}){yellow}%clr(%X{contexto}){blue} %clr(%m%n){%5p} ${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${market.app.name}]){magenta}%clr(%X{contexto}){magenta}%clr(%X{cdTransacao}){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
  level:
    com.liven: ${market.log.level}
    root: INFO
